server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-proyectos-2509/spring-cloud-config
          default-label: main
          search-paths:
           - '*service'
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t

